import "./StatsBlock.css";
export default function StatsBlock({ characterForm, formUpdate }) {
  return (
    <div className="stats-container">
      <label>
        STR(Strength)
        <input
          onChange={formUpdate}
          name="str"
          type="number"
          min="1"
          max="20"
          value={characterForm.str}
        />
      </label>
      <label>
        DEX(Dexterity)
        <input
          onChange={formUpdate}
          name="dex"
          type="number"
          min="1"
          max="20"
          value={characterForm.dex}
        />
      </label>
      <label>
        CON(Constitution)
        <input
          onChange={formUpdate}
          name="con"
          type="number"
          min="1"
          max="20"
          value={characterForm.con}
        />
      </label>
      <label>
        INT(Intelligence)
        <input
          onChange={formUpdate}
          name="int"
          type="number"
          min="1"
          max="20"
          value={characterForm.int}
        />
      </label>
      <label>
        WIS(Wisdom)
        <input
          onChange={formUpdate}
          name="wis"
          type="number"
          min="1"
          max="20"
          value={characterForm.wis}
        />
      </label>
      <label>
        CHA(Charisma)
        <input
          onChange={formUpdate}
          name="cha"
          type="number"
          min="1"
          max="20"
          value={characterForm.cha}
        />
      </label>
    </div>
  );
}
